# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20161107_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
