# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20161107_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.FileField(upload_to='', verbose_name='media'),
        ),
    ]
