# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_auto_20161108_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
