# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_deal_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
