# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_deal_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='creation_date',
        ),
    ]
